Models/Helper/Paginador.cs
using Microsoft.EntityFrameworkCore;

namespace CarSun.Models.Helper;

public class Paginador<T> where T : class
{
    #region Constructores
    public Paginador(DbSet<T> items, int paginaActual = 1, int registrosPorPagina = 10)
    {
        RegistrosPorPagina = registrosPorPagina;
        TotalRegistros = items.Count();
        TotalPaginas = (int)Math.Ceiling((double)TotalRegistros / registrosPorPagina);
        PaginaActual = (TotalPaginas < paginaActual) ? TotalPaginas : paginaActual;
        Resultado = items.Skip((((PaginaActual - 1) < 0) ? 0 : (PaginaActual - 1)) * registrosPorPagina).Take(registrosPorPagina).ToList();
    }

    public Paginador(IQueryable<T> items, int paginaActual = 1, int registrosPorPagina = 10)
    {
        RegistrosPorPagina = registrosPorPagina;
        TotalRegistros = items.Count();
        TotalPaginas = (int)Math.Ceiling((double)TotalRegistros / registrosPorPagina);
        PaginaActual = (TotalPaginas < paginaActual)? TotalPaginas : paginaActual;
        Resultado = items.Skip((((PaginaActual - 1)<0)? 0 : (PaginaActual - 1)) * registrosPorPagina).Take(registrosPorPagina).ToList();
    }
    #endregion

    #region Properties
    public int PaginaActual { get; set; }
    public int RegistrosPorPagina { get; set; }
    public int TotalRegistros { get; set; }
    public int TotalPaginas { get; set; }
    public ICollection<T> Resultado { get; set; }
    #endregion
}

Controllers/GeneracionesController.cs
using CarSun.Data;
using CarSun.Models.Helper;
using CarSun.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace CarSun.Controllers;
[Authorize]
public class GeneracionesController : Controller
{
    #region Setup contexto
    private readonly ApplicationDbContext _context;
    public GeneracionesController(ApplicationDbContext context)
    {
        _context = context;
    }
    #endregion
    #region CRUD
    public IActionResult Index(int marcaId = -1, int serieId = -1)
    {
        ViewBag.MarcaId = Selector<Marca>.GetSelectList(_context.Marcas.ToList(), "Id", "Nombre", marcaId);
        ViewBag.SerieId = Selector<Serie>.GetSelectList(_context.Series.Where(s => s.MarcaId == marcaId).ToList(), "Id", "Nombre", serieId);
        var generaciones = _context.Generaciones.Where(g => g.SerieId == serieId).ToList();
        return View(generaciones);
    }

    public IActionResult Create(int serieId = -1)
    {
        var generacion = new Generacion() { SerieId = serieId };
        ViewBag.Series = Selector<Serie>.GetSelectList(_context.Series.OrderBy(m => m.Nombre).ToList(), "Id", "Nombre", serieId);
        return View(generacion);
    }

    [HttpPost][ValidateAntiForgeryToken][Authorize(Policy = "Edit")]
    public async Task<IActionResult> Create(Generacion generacion)
    {
        try
        {
            _context.Add(generacion);
            await _context.SaveChangesAsync(true);
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View(generacion);
        }
    }

    public IActionResult Edit(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var generacion = _context.Generaciones.Include(m => m.Modelos).FirstOrDefault(m => m.Id == id);
        if (generacion is null)
        {
            return NotFound();
        }
        ViewBag.Serie = Selector<Serie>.GetSelectList(_context.Series.OrderBy(m => m.Nombre).ToList(), "Id", "Nombre", generacion.SerieId);
        return View(generacion);
    }

    [HttpPost][ValidateAntiForgeryToken][Authorize(Policy = "Edit")]
    public async Task<IActionResult> Edit(Generacion generacion)
    {
        try
        {
            _context.Update(generacion);
            await _context.SaveChangesAsync(true);
        }
        catch (DbUpdateConcurrencyException)
        {
            return View(generacion);
        }
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Delete(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var marca = _context.Generaciones.Include(x => x.Serie).FirstOrDefault(x => x.Id == id);
        if (marca is null)
        {
            return NotFound();
        }

        return View(marca);
    }

    [HttpPost][ValidateAntiForgeryToken][Authorize(Policy = "Edit")]
    public async Task<IActionResult> Delete(int id)
    {
        var generacion = _context.Generaciones.Find(id);
        if (generacion is not null)
        {
            _context.Generaciones.Remove(generacion);
            await _context.SaveChangesAsync(true);
        }
        return RedirectToAction(nameof(Index));
    }
    #endregion
}

Controllers/MarcasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CarSun.Data;
using CarSun.Models;
using Microsoft.AspNetCore.Authorization;
using CarSun.Models.Helper;

namespace CarSun.Controllers;

[Authorize]
public class MarcasController : Controller
{
    #region Setup contexto
    private readonly ApplicationDbContext _context;
    public MarcasController(ApplicationDbContext context)
    {
        _context = context;
    }
    #endregion

    #region CRUD
    public IActionResult Index(int pagina = 1, int registrosPorPagina = 10, string marcaBusqueda = "")
    {
        ViewData["marcaBusqueda"] = marcaBusqueda != string.Empty ? marcaBusqueda : ViewData["marcaBusqueda"] ?? string.Empty;
        var marcasPaginadas = new Paginador<Marca>(_context.Marcas.Where(m => m.Nombre.Contains(marcaBusqueda)).OrderBy(m => m.Nombre), pagina, registrosPorPagina);
        return View(marcasPaginadas);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost][ValidateAntiForgeryToken][Authorize(Policy = "Edit")]
    public async Task<IActionResult> Create(Marca marca)
    {
        if (ModelState.IsValid)
        {
            _context.Add(marca);
            await _context.SaveChangesAsync(true, default, marca.UserNameAudit);
            return RedirectToAction(nameof(Index));
        }
        return View(marca);
    }

    public IActionResult Edit(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var marca = _context.Marcas.Include(m => m.Series).FirstOrDefault(m => m.Id == id);
        if (marca is null)
        {
            return NotFound();
        }
        return View(marca);
    }

    [HttpPost][ValidateAntiForgeryToken][Authorize(Policy = "Edit")]
    public async Task<IActionResult> Edit(Marca marca)
    {
        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(marca);
                await _context.SaveChangesAsync(true, default, marca.UserNameAudit);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MarcaExists(marca.Id))
                {
                    return NotFound();
                }
                throw;
            }
            return RedirectToAction(nameof(Index));
        }
        return View(marca);
    }

    public IActionResult Delete(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var marca = _context.Marcas.Find(id);
        if (marca is null)
        {
            return NotFound();
        }

        return View(marca);
    }

    [HttpPost][ValidateAntiForgeryToken][Authorize(Policy = "Edit")]
    public async Task<IActionResult> Delete(int id, string? userNameAudit)
    {
        var marca = _context.Marcas.Find(id);
        if (marca is not null)
        {
            _context.Marcas.Remove(marca);
            await _context.SaveChangesAsync(true, default, userNameAudit);
        }
        return RedirectToAction(nameof(Index));
    }

    #endregion

    #region Métodos privados
    private bool MarcaExists(int id)
    {
        return _context.Marcas.Any(marca => marca.Id == id);
    }

    #endregion
}

Controllers/SeriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CarSun.Data;
using CarSun.Models;
using Microsoft.AspNetCore.Authorization;
using CarSun.Models.Helper;

namespace CarSun.Controllers;

[Authorize]
public class SeriesController : Controller
{
    #region Setup contexto
    private readonly ApplicationDbContext _context;
    public SeriesController(ApplicationDbContext context)
    {
        _context = context;
    }
    #endregion

    #region CRUD
    public IActionResult Index(int pagina = 1, int registrosPorPagina=10)
    {
        var seriesPaginadas = new Paginador<Serie>(_context.Series.Include(s => s.Marca).Include(s => s.Generaciones), pagina, registrosPorPagina);
        return View(seriesPaginadas);
    }

    public IActionResult Create(int? marcaId)
    {
        var serie = new Serie();
        if (marcaId.HasValue)
        {
            serie.MarcaId = marcaId.Value;
        }
        ViewBag.Marcas = Selector<Marca>.GetSelectList(_context.Marcas.OrderBy(m => m.Nombre).ToList(), "Id", "Nombre");
        return View(serie);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "Edit")]
    public async Task<IActionResult> Create(Serie serie)
    {
        try
        {
            _context.Add(serie);
            await _context.SaveChangesAsync(true);
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View(serie);
        }
    }

    public IActionResult Edit(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var serie = _context.Series.Include(s => s.Generaciones).FirstOrDefault(x => x.Id == id);
        if (serie is null)
        {
            return NotFound();
        }
        ViewBag.Marcas = Selector<Marca>.GetSelectList(_context.Marcas.OrderBy(m => m.Nombre).ToList(), "Id", "Nombre", serie.MarcaId);
        return View(serie);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "Edit")]
    public async Task<IActionResult> Edit(Serie serie)
    {
        try
        {
            _context.Update(serie);
            await _context.SaveChangesAsync(true);
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!SerieExists(serie.Id))
            {
                return NotFound();
            }
            return View(serie);
        }
        return RedirectToAction(nameof(Index)); 
    }

    public IActionResult Delete(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var serie = _context.Series.Include(s => s.Generaciones).Include(s => s.Marca).FirstOrDefault(s => s.Id == id);
        if (serie is null)
        {
            return NotFound();
        }
        ViewBag.NumGeneraciones = serie.Generaciones.Count;
        return View(serie);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "Edit")]
    public async Task<IActionResult> Delete(int id)
    {
        var serie = _context.Series.Find(id);
        if (serie is not null)
        {
            _context.Series.Remove(serie);
            await _context.SaveChangesAsync(true);
        }
        return RedirectToAction(nameof(Index));
    }

    #endregion

    #region Métodos privados
    private bool SerieExists(int id)
    {
        return _context.Series.Any(serie => serie.Id == id);
    }

    #endregion
}

Controllers/UserController.cs
using CarSun.Data;
using CarSun.Models;
using CarSun.Models.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SendGrid.Helpers.Mail;

namespace CarSun.Controllers;

[Authorize(Policy = "Admin")]
public class UserController : Controller
{
    #region Setup contexto
    private readonly ApplicationDbContext _context;
    private readonly UserManager<IdentityUser> _userManager;
    public UserController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }
    #endregion

    #region CRUD
    public IActionResult Index(int pagina = 1, int registrosPorPagina=10)
    {
        var usuariosPaginados = new Paginador<IdentityUser>(_context.Users, pagina, registrosPorPagina);
        return View(usuariosPaginados);
    }

    public IActionResult Edit(string id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var user = _context.Users.FirstOrDefault(x => x.Id == id);
        if (user is null)
        {
            return NotFound();
        }

        var selected = _context.UserRoles.FirstOrDefault(x => x.UserId == id)?.RoleId ?? "-1";
        var roles = new SelectList(_context.Roles, "Id", "Name", selected).ToList();
        roles.Insert(0, new SelectListItem { Text = "Ninguno", Value = "-1" });
        ViewBag.Roles = roles;
        return View(user);
    }

    [HttpPost][ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(IdentityUser user, string? rolId )
    {
        if (ModelState.IsValid)
        {
            try
            {
                _context.UserRoles.RemoveRange(_context.UserRoles.Where(r => r.UserId == user.Id));
                if (!string.IsNullOrEmpty(rolId) && !rolId.Equals("-1"))
                {
                    _context.UserRoles.Add(new IdentityUserRole<string>(){ RoleId=rolId, UserId= user.Id});
                }
                await _context.SaveChangesAsync(true);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(user.Id))
                {
                    return NotFound();
                }
                throw;
            }
            return RedirectToAction(nameof(Index));
        }
        return View(user);
    }

    public IActionResult Delete(string? id)
    {
        if (string.IsNullOrEmpty(id))
        {
            return NotFound();
        }

        var user = _context.Users.FirstOrDefault(x => x.Id == id);
        if (user is null)
        {
            return NotFound();
        }

        return View(user);
    }

    [HttpPost][ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(IdentityUser user)
    {
        try
        {
            var userToDelete = _context.Users.FirstOrDefault(u => u.Id == user.Id);
            if (userToDelete is not null)
            {
                _context.Users.Remove(userToDelete);
                await _context.SaveChangesAsync(true);
            }
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
    #endregion

    #region Métodos privados
    private bool UserExists(string id)
    {
        return _context.Users.Any(marca => marca.Id == id);
    }

    #endregion

}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarSun</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarSun.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarSun</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Marcas" asp-action="Index">Marcas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Series" asp-action="Index">Series</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Generaciones" asp-action="Index">Generaciones</a>
                            </li>
                            @if(User.IsInRole("Administrador"))
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Usuarios</a>
                            </li> 
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-1">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Paginador.cshtml
<script>
    function primeraPagina(){
        $("#pagina").val(1);
        $("#registrosPorPagina").val(@(Model.RegistrosPorPagina));
    }
    function ultimaPagina() {
        $("#pagina").val(@(Model.TotalPaginas));
        $("#registrosPorPagina").val(@Model.RegistrosPorPagina);
    }
    function anteriorPagina() {
        $("#pagina").val(@(Model.PaginaActual) - 1);
        $("#registrosPorPagina").val(@(Model.RegistrosPorPagina));
    }
    function siguientePagina() {
        $("#pagina").val(@(Model.PaginaActual) + 1);
        $("#registrosPorPagina").val(@(Model.RegistrosPorPagina));
    }
</script>


@if (Model.TotalRegistros > 0)
{
    <span class="d-none d-lg-inline">
        <strong>@Model.TotalRegistros</strong> registros encontrados<span> | </span>
    </span>
    <span>
        Página
        <input style="font-weight: bold;" value="@(Model.PaginaActual)" id="pagina"  name="pagina" type="number"
               min="1" max="@(Model.TotalPaginas)" asp-action="Index" class="form-control-sm" />
        de <strong>@Model.TotalPaginas</strong><span> | </span>
    </span>
}
else
{
    <span>No hay resultados para esta búsqueda | </span>
}

@if (Model.PaginaActual > 1)
{
    <button class="btn btn-sm btn-default" onclick="primeraPagina(); this.form.submit()">&lt;&lt;</button>
    <button class="btn btn-sm btn-default" onclick="anteriorPagina(); this.form.submit()">Anterior</button>
}
else
{
    <button class="btn btn-sm btn-default disabled" onclick="primeraPagina(); this.form.submit()">&lt;&lt;</button>
    <button class="btn btn-sm btn-default disabled" onclick="anteriorPagina(); this.form.submit()">Anterior</button>
}

@if (Model.PaginaActual < Model.TotalPaginas)
{
    <button class="btn btn-sm btn-default" onclick="siguientePagina(); this.form.submit()">Siguiente</button>
    <button class="btn btn-sm btn-default" onclick="ultimaPagina(); this.form.submit()">&gt;&gt;</button>
}
else
{
    <button class="btn btn-sm btn-default disabled" onclick="siguientePagina(); this.form.submit()">Siguiente</button>
    <button class="btn btn-sm btn-default disabled" onclick="ultimaPagina(); this.form.submit()">&gt;&gt;</button>
}
<span> | Registros por página: </span>